title: "The Infinite Lottery Paradox"
description: "A quest to understand infinity through probability theory"
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  pages:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
