Site settings
title: "The Infinity Lottery Paradox"
description: "A Journey Through Infinite Probability, Computational Limits, and the Nature of Mathematical Truth"
author: "Sohan Paul"
baseurl: ""
url: "https://24f2009295.github.io"
Build settings
markdown: kramdown
highlighter: rouge
theme: minima
Kramdown settings
kramdown:
math_engine: mathjax
syntax_highlighter: rouge
input: GFM
hard_wrap: false
MathJax configuration
mathjax:
  extensions: ["tex2jax.js"]
  jax: ["input/TeX", "output/HTML-CSS"]
  tex2jax:
    inlineMath: [["","", "
",""], ["\\(", "\\)"]]
    displayMath: [["$$", "$$"], ["\\[", "\\]"]]
    processEscapes: true
    processEnvironments: true
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
  TeX:
    equationNumbers: { autoNumber: "AMS" }
    extensions: ["AMSmath.js", "AMSsymbols.js", "color.js"]
  "HTML-CSS":
    fonts: ["TeX"]
    linebreaks: { automatic: true }
    scale: 100

Plugin settings
plugins:

jekyll-feed
jekyll-sitemap
jekyll-seo-tag

Exclude from processing
exclude:

Gemfile
Gemfile.lock
node_modules
vendor/bundle/
vendor/cache/
vendor/gems/
vendor/ruby/
